insert into event (event_nm, date_st, date_end) values ('Miami Valley Rgional', '2018-02-28', '2018-03-03');

insert into team (team_no,  team_nm) values (48, 'Delphi E.L.I.T.E.');
insert into team (team_no,  team_nm) values (63, 'McDowell Robotics Team 63');
insert into team (team_no,  team_nm) values (128, 'The Bobcats');
insert into team (team_no,  team_nm) values (144, 'The R.O.C.K.');
insert into team (team_no,  team_nm) values (234, 'Cyber Blue');
insert into team (team_no,  team_nm) values (247, 'Da Bears');
insert into team (team_no,  team_nm) values (279, 'Tech Fusion');
insert into team (team_no,  team_nm) values (291, 'CIA - Creativity In Action');
insert into team (team_no,  team_nm) values (304, 'GWHS Robo Griffins');
insert into team (team_no,  team_nm) values (337, 'Hard Working Hard Hats');
insert into team (team_no,  team_nm) values (379, 'RoboCats');
insert into team (team_no,  team_nm) values (451, 'The Cat Attack');
insert into team (team_no,  team_nm) values (554, 'The Bluegrease Crew');
insert into team (team_no,  team_nm) values (677, 'Murphy''s Outlaw');
insert into team (team_no,  team_nm) values (1014, 'Bad Robots');
insert into team (team_no,  team_nm) values (1038, 'Lakota Robotics');
insert into team (team_no,  team_nm) values (1317, 'Digital Fusion');
insert into team (team_no,  team_nm) values (1466, 'Webb Robotics');
insert into team (team_no,  team_nm) values (1559, 'Devil Tech');
insert into team (team_no,  team_nm) values (1675, 'UPS (Ultimate Protection Squad)');
insert into team (team_no,  team_nm) values (2172, 'Street Legal');
insert into team (team_no,  team_nm) values (2252, 'The Mavericks');
insert into team (team_no,  team_nm) values (2399, 'The Fighting Unicorns');
insert into team (team_no,  team_nm) values (2603, 'Steel Stingers');
insert into team (team_no,  team_nm) values (3010, 'The Red Plague');
insert into team (team_no,  team_nm) values (3138, 'Innovators Robotics');
insert into team (team_no,  team_nm) values (3193, 'Falco Tech');
insert into team (team_no,  team_nm) values (3201, 'Ross Rambotics');
insert into team (team_no,  team_nm) values (3260, 'SHARP');
insert into team (team_no,  team_nm) values (3266, 'Robots-R-Us');
insert into team (team_no,  team_nm) values (3324, 'The Metrobots');
insert into team (team_no,  team_nm) values (3397, 'Robolions');
insert into team (team_no,  team_nm) values (3484, 'Short Circuit');
insert into team (team_no,  team_nm) values (3492, 'P.A.R.T.s');
insert into team (team_no,  team_nm) values (3504, 'Girls of Steel');
insert into team (team_no,  team_nm) values (3777, 'Bean  City Bots');
insert into team (team_no,  team_nm) values (3844, 'Kentucky Wildbots');
insert into team (team_no,  team_nm) values (3940, 'CyberTooth');
insert into team (team_no,  team_nm) values (4028, 'The Beak Squad');
insert into team (team_no,  team_nm) values (4085, 'Technical Difficulties');
insert into team (team_no,  team_nm) values (4121, 'Vikings');
insert into team (team_no,  team_nm) values (4145, 'WorBots');
insert into team (team_no,  team_nm) values (4283, 'INSPIRE Robotics');
insert into team (team_no,  team_nm) values (4284, 'ScotBot4284');
insert into team (team_no,  team_nm) values (4362, 'Gems');
insert into team (team_no,  team_nm) values (4467, 'Titanium Titans');
insert into team (team_no,  team_nm) values (4521, 'Harrison Robotics');
insert into team (team_no,  team_nm) values (4611, 'O-Zone');
insert into team (team_no,  team_nm) values (5413, 'Stellar Robotics');
insert into team (team_no,  team_nm) values (5418, 'The Sonic Screwdrivers');
insert into team (team_no,  team_nm) values (5492, 'Winner''s Circle Robo Jockeys');
insert into team (team_no,  team_nm) values (5667, 'The Digital Eagles');
insert into team (team_no,  team_nm) values (5740, 'CWNC-Trojanators');
insert into team (team_no,  team_nm) values (5811, 'BONDS');
insert into team (team_no,  team_nm) values (6032, 'Pirate Robotics');
insert into team (team_no,  team_nm) values (6084, 'Swoop Robotics');
insert into team (team_no,  team_nm) values (6460, 'Air Guardians');
insert into team (team_no,  team_nm) values (6765, 'Columbus City Schools Walnut Ridge Scotts');
insert into team (team_no,  team_nm) values (6834, 'Bionic Warriors');
insert into team (team_no, team_nm) values (6927, 'The Franklinton Firebirds');
insert into team (team_no, team_nm) values (6936, 'The Beaver Bots - Vault 6936');
insert into team (team_no, team_nm) values (7165, 'Perkins Pirates');

insert into event_team_xref (team_no,  event_id) values (48, 1);
insert into event_team_xref (team_no,  event_id) values (63, 1);
insert into event_team_xref (team_no,  event_id) values (128, 1);
insert into event_team_xref (team_no,  event_id) values (144, 1);
insert into event_team_xref (team_no,  event_id) values (234, 1);
insert into event_team_xref (team_no,  event_id) values (247, 1);
insert into event_team_xref (team_no,  event_id) values (279, 1);
insert into event_team_xref (team_no,  event_id) values (291, 1);
insert into event_team_xref (team_no,  event_id) values (304, 1);
insert into event_team_xref (team_no,  event_id) values (337, 1);
insert into event_team_xref (team_no,  event_id) values (379, 1);
insert into event_team_xref (team_no,  event_id) values (451, 1);
insert into event_team_xref (team_no,  event_id) values (554, 1);
insert into event_team_xref (team_no,  event_id) values (677, 1);
insert into event_team_xref (team_no,  event_id) values (1014, 1);
insert into event_team_xref (team_no,  event_id) values (1038, 1);
insert into event_team_xref (team_no,  event_id) values (1317, 1);
insert into event_team_xref (team_no,  event_id) values (1466, 1);
insert into event_team_xref (team_no,  event_id) values (1559, 1);
insert into event_team_xref (team_no,  event_id) values (1675, 1);
insert into event_team_xref (team_no,  event_id) values (2172, 1);
insert into event_team_xref (team_no,  event_id) values (2252, 1);
insert into event_team_xref (team_no,  event_id) values (2399, 1);
insert into event_team_xref (team_no,  event_id) values (2603, 1);
insert into event_team_xref (team_no,  event_id) values (3010, 1);
insert into event_team_xref (team_no,  event_id) values (3138, 1);
insert into event_team_xref (team_no,  event_id) values (3193, 1);
insert into event_team_xref (team_no,  event_id) values (3201, 1);
insert into event_team_xref (team_no,  event_id) values (3260, 1);
insert into event_team_xref (team_no,  event_id) values (3266, 1);
insert into event_team_xref (team_no,  event_id) values (3324, 1);
insert into event_team_xref (team_no,  event_id) values (3397, 1);
insert into event_team_xref (team_no,  event_id) values (3484, 1);
insert into event_team_xref (team_no,  event_id) values (3492, 1);
insert into event_team_xref (team_no,  event_id) values (3504, 1);
insert into event_team_xref (team_no,  event_id) values (3777, 1);
insert into event_team_xref (team_no,  event_id) values (3844, 1);
insert into event_team_xref (team_no,  event_id) values (3940, 1);
insert into event_team_xref (team_no,  event_id) values (4028, 1);
insert into event_team_xref (team_no,  event_id) values (4085, 1);
insert into event_team_xref (team_no,  event_id) values (4121, 1);
insert into event_team_xref (team_no,  event_id) values (4145, 1);
insert into event_team_xref (team_no,  event_id) values (4283, 1);
insert into event_team_xref (team_no,  event_id) values (4284, 1);
insert into event_team_xref (team_no,  event_id) values (4362, 1);
insert into event_team_xref (team_no,  event_id) values (4467, 1);
insert into event_team_xref (team_no,  event_id) values (4521, 1);
insert into event_team_xref (team_no,  event_id) values (4611, 1);
insert into event_team_xref (team_no,  event_id) values (5413, 1);
insert into event_team_xref (team_no,  event_id) values (5418, 1);
insert into event_team_xref (team_no,  event_id) values (5492, 1);
insert into event_team_xref (team_no,  event_id) values (5667, 1);
insert into event_team_xref (team_no,  event_id) values (5740, 1);
insert into event_team_xref (team_no,  event_id) values (5811, 1);
insert into event_team_xref (team_no,  event_id) values (6032, 1);
insert into event_team_xref (team_no,  event_id) values (6084, 1);
insert into event_team_xref (team_no,  event_id) values (6460, 1);
insert into event_team_xref (team_no,  event_id) values (6765, 1);
insert into event_team_xref (team_no,  event_id) values (6834, 1);
insert into event_team_xref (team_no, event_id) values (6927, 1);
insert into event_team_xref (team_no, event_id) values (6936, 1);
insert into event_team_xref (team_no, event_id) values (7165, 1);